include("../model/Alakazam.jl")
include("../model/Blastoise.jl")
include("../model/Blaziken.jl")
include("../model/Charizard.jl")
include("../model/Crobat.jl")
include("../model/Gengar.jl")
include("../model/Gyarados.jl")
include("../model/Marowak.jl")
include("../model/Raichu.jl")
include("../model/Sceptile.jl")
include("../model/Slowbro.jl")
include("../model/Snorlax.jl")
include("../model/Venusaur.jl")

listaPokemon = [
    alakazam,
    blastoise,
    blaziken,
    charizard,
    crobat,
    gengar,
    gyarados,
    marowak,
    raichu,
    sceptile,
    slowbro,
    snorlax,
    venusaur
]